# Generated by Django 4.1.7 on 2023-02-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='markets.item')),
            ],
        ),
    ]
