# Generated by Django 4.1.7 on 2023-03-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='seller',
            new_name='item',
        ),
    ]
