# Generated by Django 4.1.7 on 2023-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.FloatField(),
        ),
    ]
